meta_product_name: "Restaurant Advisor"
meta_title: "Restaurant Advisor. All the Restaurants... All in One Place. "
meta_description: "Find great restaurants in your area."
meta_image: "cover.png" # should exist in `app/assets/images/`
