meta_product_name: "John Haus"
meta_title: "John Haus - Full stack web developer"
meta_description: "I build web applications with Ruby on Rails and React"
meta_image: "cover.png" # should exist in `app/assets/images/`
